// Define all possible rights in the POS system
export const RIGHTS = {
  // User Management Rights
  CREATE_USER: 'CREATE_USER',
  VIEW_USER: 'VIEW_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  MANAGE_USER_PERMISSIONS: 'MANAGE_USER_PERMISSIONS',
  RESET_USER_PASSWORD: 'RESET_USER_PASSWORD',

  // Product Management Rights
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  VIEW_PRODUCT: 'VIEW_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  MANAGE_PRODUCT_PRICING: 'MANAGE_PRODUCT_PRICING',
  MANAGE_PRODUCT_DISCOUNTS: 'MANAGE_PRODUCT_DISCOUNTS',

  // Inventory Management Rights
  VIEW_INVENTORY: 'VIEW_INVENTORY',
  UPDATE_INVENTORY: 'UPDATE_INVENTORY',
  MANAGE_SUPPLIERS: 'MANAGE_SUPPLIERS',
  VIEW_SUPPLY_CHAIN: 'VIEW_SUPPLY_CHAIN',

  // Sales and Transaction Rights
  CREATE_TRANSACTION: 'CREATE_TRANSACTION',
  VIEW_TRANSACTION: 'VIEW_TRANSACTION',
  UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
  DELETE_TRANSACTION: 'DELETE_TRANSACTION',
  PROCESS_REFUND: 'PROCESS_REFUND',
  APPLY_DISCOUNT: 'APPLY_DISCOUNT',

  // Customer Management Rights
  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  VIEW_CUSTOMER: 'VIEW_CUSTOMER',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  DELETE_CUSTOMER: 'DELETE_CUSTOMER',

  // Reporting and Analytics Rights
  VIEW_SALES_REPORTS: 'VIEW_SALES_REPORTS',
  VIEW_INVENTORY_REPORTS: 'VIEW_INVENTORY_REPORTS',
  VIEW_FINANCIAL_REPORTS: 'VIEW_FINANCIAL_REPORTS',
  EXPORT_REPORTS: 'EXPORT_REPORTS',

  // System Configuration Rights
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  MANAGE_PAYMENT_METHODS: 'MANAGE_PAYMENT_METHODS',
  MANAGE_TAX_SETTINGS: 'MANAGE_TAX_SETTINGS',
  CONFIGURE_NOTIFICATIONS: 'CONFIGURE_NOTIFICATIONS',
  CONFIGURE_AUDIT_LOGS: 'CONFIGURE_AUDIT_LOGS',

  // Access Control Rights
  VIEW_PERMISSIONS: 'VIEW_PERMISSIONS',
  ASSIGN_PERMISSIONS: 'ASSIGN_PERMISSIONS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  MANAGE_TWO_FACTOR_AUTH: 'MANAGE_TWO_FACTOR_AUTH',

  // Developer and System Maintenance Rights
  VIEW_SYSTEM_LOGS: 'VIEW_SYSTEM_LOGS',
  DEBUG_SYSTEM: 'DEBUG_SYSTEM',
  DEPLOY_UPDATES: 'DEPLOY_UPDATES',
  ACCESS_API: 'ACCESS_API',
  PERFORM_BACKUP: 'PERFORM_BACKUP',
  CONFIGURE_INTEGRATIONS: 'CONFIGURE_INTEGRATIONS',
};

// Example usage: assign rights to roles
export const ROLES = {
  CASHIER: [
    RIGHTS.CREATE_TRANSACTION,
    RIGHTS.VIEW_TRANSACTION,
    RIGHTS.APPLY_DISCOUNT,
    RIGHTS.CREATE_CUSTOMER,
    RIGHTS.VIEW_CUSTOMER,
  ],
  MANAGER: [
    RIGHTS.CREATE_TRANSACTION,
    RIGHTS.VIEW_TRANSACTION,
    RIGHTS.UPDATE_TRANSACTION,
    RIGHTS.PROCESS_REFUND,
    RIGHTS.CREATE_CUSTOMER,
    RIGHTS.VIEW_CUSTOMER,
    RIGHTS.UPDATE_CUSTOMER,
    RIGHTS.VIEW_INVENTORY,
    RIGHTS.VIEW_SALES_REPORTS,
    RIGHTS.VIEW_INVENTORY_REPORTS,
  ],
  ADMIN: Object.values(RIGHTS), // Full access to all rights
  DEVELOPER: [
    RIGHTS.VIEW_SYSTEM_LOGS,
    RIGHTS.DEBUG_SYSTEM,
    RIGHTS.DEPLOY_UPDATES,
    RIGHTS.ACCESS_API,
    RIGHTS.CONFIGURE_INTEGRATIONS,
  ],
};
